### PR TITLE
Improved FFTW config

### PR DESCRIPTION
**Pull request by geraintluff**
The benchmark currently uses `FFTW_ESTIMATE`, which uses pre-packaged heuristics to choose its plans.  This is fine for single FFTs, but for multiple uses, other modes are faster.

`FFTW_MEASURE` enables runtime profiling to find a fast plan, as recommended in this [tutorial page](http://www.fftw.org/fftw3_doc/Complex-One_002dDimensional-DFTs.html#Complex-One_002dDimensional-DFTs).  This has some set-up cost, but I think it makes sense for a benchmark.

Here are a couple of graphs, illustrating the performance difference between the modes:

graph-fftw-performance-small

graph-fftw-performance-larg

_(Graphs taken from my WIP, which is how I figured this out.)_

As the graphs show, `FFTW_PATIENT` gets even faster results, but plan-searching is very slow for large sizes (e.g. 2^18), which is why I've suggested `FFTW_MEASURE` in this PR.  The ideal solution probably uses `FFTW_EXHAUSTIVE` along with [`fftw_set_timelimit()`](http://www.fftw.org/fftw3_doc/Planner-Flags.html) to limit the search time to some fixed number of seconds.

The plan-profiling uses the input/output arrays, which is why I have moved the benchmark object construction to before the random-data generation.

### CODE REVIEW

**Comment by dancasarin** [comment]
Hi,

In the current benchmark all results for the tested libraries are obtained under equal conditions.
KFR is built using AVX2 on Clang 7.0.
IPP and FFTW are prebuilt by their developers with support for architectures up to AVX2.
IPP and FFTW in ESTIMATE mode detect cpu instruction set, 
cache size and use only this information to choose best algorithm or combination of algorithms available in prebuilt binary.

By allowing FFTW to try its algorithms right on the cpu before actual run we would put the libraries in unequal conditions.
As soon as similar feature will be supported in IPP and KFR this mode will be added to the benchmark code.

KFR is designed primarily for Audio and DSP.
It's not usual to do such long runtime tests before starting the application or plugin on an end-user machine.
(for 16777216 size it's ~18 minutes in PATIENT mode, 14 seconds for MEASURE which is also sufficient time).

Also, you can provide the following details to make comparison more specific:
* Library versions (and commit hash for KFR) used in your benchmark
* Architecture and instruction set used for building.
* CPU used for testing.

If you did not use the current benchmark code:
* How many runs executed (or how much time spent) for each size.
* How the final result are calculated? Minimum/average/median time?
* How the normalized performance is calculated?
* Does it subtract time measurement overhead?

The library versions and target architecture used for the current benchmark are shown on the screenshots.
Other details are in the code. The CPU used for the published results is Core i7 8770K. Other AVX and AVX2-capable CPU show very similar results.

**Comment by geraintluff** [comment]
Thanks for responding!  This might be a philosophical difference - I personally think that a good benchmark lets each library show their best.

I expect that people who care about benchmark results are interested in the _possible_ performance they could get - after that, they can balance it against other factors (such as implementation complexity, executable size, or startup cost) and make an informed choice.

So, I'm not sure I agree about the equal conditions.  As an example: my implementation doesn't support AVX.  If I said my "equal conditions" were to only use features that _all_ the libraries support, and therefore compiled KFR without AVX/AVX2 to get this graph:

screenshot 2019-02-07 at 21 17 37

... it would be much more flattering (for me!), but I expect you'd dispute the validity of those results.

(Also FWIW, the FFTW analysis is a truly one-time cost - you can save that profile as a string and store it in a file, so it only needs to be run once on each machine, not every time it's loaded.  And yeah, `FFTW_PATIENT` can be super-long, which is why I suggested `FFTW_MEASURE`, although `fftw_set_timelimit()` would be even better.)

-----

I didn't want to get too specific about methodology, because I'm not holding up these graphs as definitive!  I was using the results to show that there's a notable difference between `FFTW_ESTIMATE` and `FFTW_MEASURE`.  However, since you asked:

Versions:

- Apple LLVM version 9.1.0 (clang-902.0.39.2)
- Target: x86_64-apple-darwin18.2.0
- 1.6 GHz Intel Core i5
- 4 GB 1600 MHz DDR3
- KFR 3.0.3 (`cb4f45604da3a2eabf6c0c7f5b73151dc24370fc`), which was `master` on GitHub at the time.
- compiled with `-O3 -msse2 -mavx -mavx2` (`g++` interface)

Benchmark calculations - hacky and approximate as they are:

- a minimum target of 2 seconds (clock time) for each size, for each candidate
- performed as 10 sets of 0.2s, the fastest 50% of those 0.2s blocks are taken as the result
- normalised performance is `(total iterations / total seconds) * 0.00000001 * N*log(N)`.
- it doesn't compensate for time-measurement overhead, but it uses previous estimates to guess the number of repeats required, so most 0.2s blocks will only have one or two time-measurements

I didn't keep the total number of iterations, but a minimum can be worked out.  So, for `N=65536`, KFR scored around `14`, which means it's at least `3850` repeats overall.  It will have done fewer repeats for larger `N`, down to a handful of repeats each for `16777216`.

(It's also worth noting that I ended up compiling FFTW myself, instead of downloading a pre-build library, so I might not have compiled that optimally either.  As I said, I'm not claiming these results as definitive.)

--------

I'm not looking to campaign on this issue  - it's not my fight, I'm not an FFTW dev, and in reality I'm not looking to compete with either KFR or FFTW.  (My implementation is a single 600-line header-file, so my real competition here is KissFFT! 😉)

I only thought I'd let you know of this issue in case you weren't aware.  I personally had misunderstood what your graphs implied, and only realised when I ran my own benchmarks (and noticed I wasn't using `FFTW_MEASURE` either, which took me a while!).

Maybe there's another solution than this PR, like adding a brief note to explain which FFTW configuration you compared against, given that they're so different.  Feel free to resolve this however you like. 🙂

**Comment by dancasarin** [comment]
Here are the results of switching to FFTW_MEASURE.

powers2_double_16_16777216
It's obtained on the same machine (8770K up to 4.6GHz/32GB DDR4)

All benchmark code used for FFT comparison is published and reproducible.

You haven't specified cpu model, cache size and versions for IPP and FFTW.

**Comment by geraintluff** [comment]
Cool!  Yeah, that's quite a difference, with FFTW running almost twice as fast for some sizes. 🙂

Perhaps I shouldn't have included my hacked-together mid-development graphs at all.  I thought they'd be a casual illustration, but we ended up fixated on how I got those exact results, instead of the general idea that FFTW_MEASURE has better performance (which was the point of this PR, and your graph also supports).

I also realised that the precompiled FFTWs generally don't include AVX2 ([link](http://www.fftw.org/release-notes.html)), and that's what you're comparing against.  However, since I was building FFTW myself, I used `--enable-avx2`, which might explain some things as well.

Thanks for taking the time to look at this.

**Pull request closed without merging**
